---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meditrack
  name: patient-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: patient-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: patient-app
    spec:
      containers:
      - image: 529088288184.dkr.ecr.us-east-1.amazonaws.com/meditrack-patient-record:latest
        imagePullPolicy: Always
        name: patient-app
        ports:
        - containerPort: 3034
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: meditrack
  name: patient-record
spec:
  ports:
    - port: 3034
      targetPort: 3034
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: patient-app
status:
  loadBalancer: {}