---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meditrack
  name: patient-deploy-green
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: patient-app-green
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: patient-app-green
    spec:
      containers:
      - image: 529088288184.dkr.ecr.us-east-1.amazonaws.com/meditrack-patient-record:latest
        imagePullPolicy: Always
        name: patient-app-green
        ports:
        - containerPort: 3040
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: meditrack
  name: patient-record-green
spec:
  ports:
    - port: 3040
      targetPort: 3040
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: patient-app-green
status:
  loadBalancer: {}