apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      version: green
  template:
    metadata:
      labels:
        app: notification-service
        version: green

    spec:
      containers:
      - name: notification-service
        image: registry.digitalocean.com/meditrackcontainer/notification-service:green
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: do-secret

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-green
spec:
  selector:
    app: notification-service
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
