apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator-cronjob
spec:
  schedule: "30 18 * * *" # Run at 1 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregator
            image: registry.digitalocean.com/meditrackcontainer/aggregate-service:latest
            imagePullPolicy: Always
            
          imagePullSecrets:
          - name: do-secret
          restartPolicy: Never

