apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-record-service
      version: green
  template:
    metadata:
      labels:
        app: patient-record-service
        version: green

    spec:
      containers:
      - name: patient-record-service
        image: registry.digitalocean.com/meditrackcontainer/patient-record:green
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: do-secret

---
apiVersion: v1
kind: Service
metadata:
  name: patient-record-service-green
spec:
  selector:
    app: patient-record-service
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
